### ISSUE TITLE
Sometimes the thumbnails are lost after the recording is completed.

### ISSUE THREAD

**Issue by timmyhbk** [herowinb/live-dl#26] opened 2024-08-18 07:04 UTC
**Describe the bug**

![20240815 【900k Unarchived Karaoke】yayyyy (PDi1kYQ5py0)](https://github.com/user-attachments/assets/50835584-d781-4ed6-9a24-556bdf74e032)
Sometimes the thumbnails are lost after the recording is completed. It becomes like this.
Thumbnails are downloaded correctly during the recording, but sometimes they are replaced by this image after the live stream ends (recording is complete).
This doesn't always happen. Can't find a pattern to it.

**To Reproduce**
1. Run auto.sh.
2. The error

**Desktop (please complete the following information):**
 - OS: Docker @ Synology NAS
 - Version last updated

**Comment by herowinb** [comment] 2024-08-18 07:08
Let me guess, it only happens to Unarchive streams right ? If yes, then the problem is the stream already privated, deleted because LiveDL could redownload the thmabnail.

**Comment by timmyhbk** [comment] 2024-08-18 07:13
It does seem to be the case. Is there any way to avoid this.

**Comment by herowinb** [comment] 2024-08-18 08:00
Just add a line to skip redownload thumbnail if it not found.
It should be fixed now.

**Closed by herowinb** 2024-08-18 08:00 UTC
Labels: bug
